[package]
name = "idx-dsl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
idx = { path = "../idx" }
syn = { version = "1.0.86", features = ["full", "parsing", "proc-macro", "extra-traits"] }
quote = "1.0.15"